/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ToDo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Todolist extends javax.swing.JFrame {

 
    public Todolist() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txttask = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ToDo List");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AddTask", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Banner", 0, 18))); // NOI18N

        jLabel2.setText("Name :");

        jLabel3.setText("Mobile No:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Task :");

        txttask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttaskActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttask, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtname)
                        .addComponent(txtmobile, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txttask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(52, 52, 52))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile No", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttaskActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              // TODO add your handling code here:
             DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
             int selectedIndex = jTable1.getSelectedRow();
             
              try {
                  
                  int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
                  String name = txtname.getText();
                  String mobile = txtmobile.getText();
                  String task = txttask.getText();
                  
                  
                  
                      Class.forName("com.mysql.cj.jdbc.Driver");
              try {
                con1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/mahir_26","mahir2003","Mahir@2003");
                  insert = con1.prepareStatement("update record set name=?,mobile=?,task=? where id=?");
                  insert.setString(1,name);
                  insert.setString(2,mobile);
                  insert.setString(3,task);
                  insert.setInt(4,id);
                  
                  
                  insert.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Record Update ");
                  table_update();
                  txtname.setText("");
                  txtmobile.setText("");
                  txttask.setText("");
                  txtname.requestFocus();
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
              }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
        }
             
              
    }//GEN-LAST:event_jButton2ActionPerformed

          Connection con1;
         PreparedStatement insert;
          
          
          
          
          
          private void table_update(){
              int c;
                try {
                      Class.forName("com.mysql.cj.jdbc.Driver");
              try {
           
                con1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/mahir_26","mahir2003","Mahir@2003");
                    insert = con1.prepareStatement("select * from record");
                    ResultSet rs = insert.executeQuery();
                    ResultSetMetaData Rss = rs.getMetaData();
                    c = Rss.getColumnCount();
                    
                    DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                    Df.setRowCount(0);
                    
                    while(rs.next()){
                        Vector v2 = new Vector();
                        
                        for(int i=1;i<=c;i++){
                            v2.add(rs.getString("id"));
                            v2.add(rs.getString("name"));
                            v2.add(rs.getString("mobile"));
                            v2.add(rs.getString("Task"));
                        }
                        
                        Df.addRow(v2);
                    }
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
              }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
        }
              
          }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                   // TODO add your handling code here:
          String name = txtname.getText();
          String mobile = txtmobile.getText();
          String task = txttask.getText();
     
        try {
                      Class.forName("com.mysql.cj.jdbc.Driver");
              try {
                con1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/mahir_26","mahir2003","Mahir@2003");
                  insert = con1.prepareStatement("insert into record(name,mobile,Task)values(?,?,?)");
                  insert.setString(1,name);
                  insert.setString(2,mobile);
                  insert.setString(3,task);
                  insert.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Record Addedd");
                  table_update();
                  txtname.setText("");
                  txtmobile.setText("");
                  txttask.setText("");
                  txtname.requestFocus();
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
              }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
        }
          
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                   // TODO add your handling code here:
                   DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                   int selectedIndex = jTable1.getSelectedRow();
                   
                   
                   txtname.setText(Df.getValueAt(selectedIndex, 1).toString());
                   txtmobile.setText(Df.getValueAt(selectedIndex, 2).toString());
                   txttask.setText(Df.getValueAt(selectedIndex, 3).toString());
                   
                  
                   
                   
                   
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
                
                 DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
                 int selectedIndex = jTable1.getSelectedRow();
                 
                               try {
                  
                  int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
                  
                  int dialogResult = JOptionPane.showConfirmDialog(null,"Do You want to Delete the Record", "Warning",JOptionPane.YES_NO_OPTION);
                  
                  if(dialogResult == JOptionPane.YES_OPTION){
                      
                       Class.forName("com.mysql.cj.jdbc.Driver");
                       con1 = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/mahir_26","mahir2003","Mahir@2003");
                       insert = con1.prepareStatement("delete from  record where id=?");
                       
                       insert.setInt(1,id);
            
                  }
        
              try {
             
                  
                  
                  insert.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Record Delete ");
                  table_update();
                  txtname.setText("");
                  txtmobile.setText("");
                  txttask.setText("");
                  txtname.requestFocus();
                  
              } catch (SQLException ex) {
                  Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
              }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Todolist.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
                 
                 
            
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Todolist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Todolist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttask;
    // End of variables declaration//GEN-END:variables
}
